INSERT INTO cars 
(name, brand, year, price, images, condition, fuel, transmission, color, description, is_promo)
VALUES
('Toyota Corolla LE', 'Toyota', 2021, 14500, array['/cars/corolla1.jpg','/cars/corolla2.jpg'], NULL, 'Petrol', 'Automatic', 'Silver', 'Reliable sedan perfect for everyday use.', TRUE),
('Honda Accord EX', 'Honda', 2020, 16200, array['/cars/accord1.jpg','/cars/accord2.jpg'], NULL, 'Petrol', 'Automatic', 'White', 'Comfortable mid-size car with strong resale value.', TRUE),
('Nissan Sentra SV', 'Nissan', 2021, 13800, array['/cars/sentra1.jpg','/cars/sentra2.jpg'], NULL, 'Petrol', 'Automatic', 'Blue', 'Efficient compact sedan ideal for city driving.', TRUE),
('Hyundai Elantra SEL', 'Hyundai', 2022, 15000, array['/cars/elantra1.jpg','/cars/elantra2.jpg'], NULL, 'Petrol', 'Automatic', 'Grey', 'Sleek design and modern tech for less.', TRUE),
('Kia Rio LX', 'Kia', 2020, 9800, array['/cars/rio1.jpg','/cars/rio2.jpg'], NULL, 'Petrol', 'Manual', 'Red', 'Affordable compact car with great fuel economy.', TRUE),
('Mazda 3 Touring', 'Mazda', 2021, 14200, array['/cars/mazda3_1.jpg','/cars/mazda3_2.jpg'], NULL, 'Petrol', 'Automatic', 'Black', 'Smooth handling with stylish looks.', TRUE),
('Volkswagen Jetta SE', 'Volkswagen', 2021, 14800, array['/cars/jetta1.jpg','/cars/jetta2.jpg'], NULL, 'Petrol', 'Automatic', 'White', 'Refined ride with a comfortable cabin.', TRUE),
('Chevrolet Malibu LT', 'Chevrolet', 2020, 13600, array['/cars/malibu1.jpg','/cars/malibu2.jpg'], NULL, 'Petrol', 'Automatic', 'Grey', 'Spacious and reliable mid-size sedan.', TRUE),
('Ford Focus SE', 'Ford', 2019, 11000, array['/cars/focus1.jpg','/cars/focus2.jpg'], NULL, 'Petrol', 'Automatic', 'Blue', 'Fun-to-drive compact car with great value.', TRUE),
('Toyota Yaris', 'Toyota', 2020, 9800, array['/cars/yaris1.jpg','/cars/yaris2.jpg'], NULL, 'Petrol', 'Automatic', 'White', 'Compact and efficient daily driver.', TRUE),
('Honda Fit', 'Honda', 2020, 10500, array['/cars/fit1.jpg','/cars/fit2.jpg'], NULL, 'Petrol', 'Manual', 'Silver', 'Versatile hatchback with roomy interior.', TRUE),
('Hyundai Accent', 'Hyundai', 2021, 9900, array['/cars/accent1.jpg','/cars/accent2.jpg'], NULL, 'Petrol', 'Automatic', 'Red', 'Budget-friendly sedan with good performance.', TRUE),
('Kia Soul', 'Kia', 2021, 12800, array['/cars/soul1.jpg','/cars/soul2.jpg'], NULL, 'Petrol', 'Automatic', 'Yellow', 'Unique design and roomy cargo space.', TRUE),
('Nissan Versa', 'Nissan', 2022, 9700, array['/cars/versa1.jpg','/cars/versa2.jpg'], NULL, 'Petrol', 'Automatic', 'Black', 'Compact and affordable, great for first-time buyers.', TRUE),
('Toyota Highlander', 'Toyota', 2021, 22500, array['/cars/highlander1.jpg','/cars/highlander2.jpg'], NULL, 'Petrol', 'Automatic', 'Grey', 'Family SUV with advanced safety features.', TRUE),
('Mazda CX-5', 'Mazda', 2021, 19800, array['/cars/cx5_1.jpg','/cars/cx5_2.jpg'], NULL, 'Petrol', 'Automatic', 'Blue', 'Compact SUV with premium interior.', TRUE),
('Hyundai Tucson', 'Hyundai', 2021, 18200, array['/cars/tucson1.jpg','/cars/tucson2.jpg'], NULL, 'Petrol', 'Automatic', 'White', 'Reliable SUV for modern families.', TRUE),
('Ford Escape', 'Ford', 2020, 17600, array['/cars/escape1.jpg','/cars/escape2.jpg'], NULL, 'Petrol', 'Automatic', 'Green', 'Compact SUV with smooth driving experience.', TRUE),
('Chevrolet Equinox', 'Chevrolet', 2021, 18900, array['/cars/equinox1.jpg','/cars/equinox2.jpg'], NULL, 'Petrol', 'Automatic', 'Silver', 'Comfortable SUV for all your adventures.', TRUE),
('Subaru Forester', 'Subaru', 2021, 21000, array['/cars/forester1.jpg','/cars/forester2.jpg'], NULL, 'Petrol', 'Automatic', 'White', 'All-wheel-drive SUV built for safety and reliability.', TRUE);


insert into cars (name, brand, year, price, images, condition, fuel, transmission, color, description, is_promo) values
('Aventador SVJ','Lamborghini',2020,450000,array['/cars/lamborghini1.jpg','/cars/lamborghini2.jpg'],'used','Petrol','Automatic','Yellow','V12 supercar in great condition.', false),
('911 Turbo S','Porsche',2021,220000,array['/cars/porsche1.jpg','/cars/porsche2.jpg'],'new','Petrol','Automatic','Black','Immaculate performance car.', false),
('Model S Plaid','Tesla',2022,130000,array['/cars/tesla1.jpg','/cars/tesla2.jpg'],'new','Electric','Automatic','White','Electric hypercar with insane acceleration.', false),
('Mustang GT','Ford',2019,55000,array['/cars/ford1.jpg','/cars/ford2.jpg'],'used','Petrol','Manual','Red','Classic American muscle with roaring V8.', false),
('Camry XSE','Toyota',2022,35000,array['/cars/toyota1.jpg','/cars/toyota2.jpg'],'new','Petrol','Automatic','Blue','Reliable sedan with sporty trim.', false),
('Civic Type R','Honda',2021,42000,array['/cars/honda1.jpg','/cars/honda2.jpg'],'used','Petrol','Manual','White','High-performance hot hatch.', false),
('A4 Quattro','Audi',2020,39000,array['/cars/audi1.jpg','/cars/audi2.jpg'],'used','Petrol','Automatic','Silver','Luxury sedan with AWD handling.', false),
('X5 M50i','BMW',2022,88000,array['/cars/bmw1.jpg','/cars/bmw2.jpg'],'new','Petrol','Automatic','Black','Luxury SUV with powerful performance.', false),
('Range Rover Sport','Land Rover',2021,99000,array['/cars/range1.jpg','/cars/range2.jpg'],'used','Diesel','Automatic','Grey','Luxury off-road capable SUV.', false),
('Chiron','Bugatti',2020,3000000,array['/cars/bugatti1.jpg','/cars/bugatti2.jpg'],'used','Petrol','Automatic','Blue','World’s fastest hypercar.', false),
('Corvette Stingray','Chevrolet',2021,65000,array['/cars/chevy1.jpg','/cars/chevy2.jpg'],'new','Petrol','Automatic','Yellow','Affordable American supercar.', false),
('Panamera','Porsche',2019,89000,array['/cars/porsche3.jpg','/cars/porsche4.jpg'],'used','Petrol','Automatic','Black','Luxury sports sedan with comfort.', false),
('S-Class','Mercedes-Benz',2022,120000,array['/cars/mercedes1.jpg','/cars/mercedes2.jpg'],'new','Petrol','Automatic','Silver','Ultimate luxury sedan.', false),
('G-Wagon G63','Mercedes-Benz',2021,200000,array['/cars/mercedes3.jpg','/cars/mercedes4.jpg'],'used','Petrol','Automatic','Black','Iconic luxury SUV.', false),
('Cherokee Trailhawk','Jeep',2020,42000,array['/cars/jeep1.jpg','/cars/jeep2.jpg'],'used','Petrol','Automatic','Green','Rugged SUV built for adventure.', false),
('Impreza WRX STI','Subaru',2019,38000,array['/cars/subaru1.jpg','/cars/subaru2.jpg'],'used','Petrol','Manual','Blue','Rally-bred sports sedan.', false),
('CX-5','Mazda',2021,32000,array['/cars/mazda1.jpg','/cars/mazda2.jpg'],'new','Petrol','Automatic','White','Stylish compact SUV.', false),
('Huracán EVO','Lamborghini',2021,270000,array['/cars/lamborghini3.jpg','/cars/lamborghini4.jpg'],'new','Petrol','Automatic','Orange','Exotic Italian supercar.', false),
('F8 Tributo','Ferrari',2020,280000,array['/cars/ferrari1.jpg','/cars/ferrari2.jpg'],'used','Petrol','Automatic','Red','Breathtaking performance and design.', false),
('LaFerrari','Ferrari',2019,1500000,array['/cars/ferrari3.jpg','/cars/ferrari4.jpg'],'used','Hybrid','Automatic','Red','Rare hybrid hypercar.', false),
('Defender','Land Rover',2022,60000,array['/cars/landrover1.jpg','/cars/landrover2.jpg'],'new','Diesel','Automatic','White','Modern off-road legend.', false),
('Cybertruck','Tesla',2023,69000,array['/cars/tesla3.jpg','/cars/tesla4.jpg'],'new','Electric','Automatic','Silver','Futuristic electric pickup.', false),
('Altima SR','Nissan',2021,29000,array['/cars/nissan1.jpg','/cars/nissan2.jpg'],'new','Petrol','Automatic','Grey','Mid-size sedan with comfort.', false),
('RX 350','Lexus',2022,50000,array['/cars/lexus1.jpg','/cars/lexus2.jpg'],'new','Petrol','Automatic','Black','Luxury crossover SUV.', false),
('Urus','Lamborghini',2021,250000,array['/cars/lamborghini5.jpg','/cars/lamborghini6.jpg'],'used','Petrol','Automatic','Yellow','High-performance luxury SUV.', false);
